/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#c1c7cf',
        'on-surface-variant': '#64748b',
        'primary-fixed': '#dae2fd',
        'secondary-fixed-dim': '#3cddc7',
        'on-primary-fixed': '#131b2e',
        'tertiary-container': '#161c22',
        'inverse-on-surface': '#eaf1ff',
        'on-tertiary-fixed-variant': '#41474e',
        'surface-bright': '#ffffff',
        'surface-variant': '#f1f5f9',
        'surface-container-highest': '#e2e8f0',
        'on-primary': '#ffffff',
        outline: '#e2e8f0',
        'on-tertiary-container': '#7e848c',
        'surface-container': '#f8fafc',
        'secondary-fixed': '#62fae3',
        'on-primary-fixed-variant': '#3f465c',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#007165',
        tertiary: '#000000',
        'outline-variant': '#f1f5f9',
        'inverse-primary': '#bec6e0',
        'on-secondary-fixed': '#00201c',
        primary: '#2563eb',
        background: '#ffffff',
        'on-background': '#0f172a',
        'surface-dim': '#f1f5f9',
        'on-surface': '#0f172a',
        error: '#ef4444',
        'primary-fixed-dim': '#bec6e0',
        'on-primary-container': '#1e40af',
        'surface-container-low': '#f8fafc',
        'on-secondary-fixed-variant': '#005047',
        'on-secondary': '#ffffff',
        secondary: '#2563eb',
        'surface-container-high': '#f1f5f9',
        'inverse-surface': '#0f172a',
        'secondary-container': '#dbeafe',
        'error-container': '#fee2e2',
        'tertiary-fixed': '#dde3eb',
        surface: '#ffffff',
        'primary-container': '#eff6ff',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#161c22',
        'surface-tint': '#2563eb',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '16px',
        gutter: '32px',
        lg: '24px',
        xs: '4px',
        'container-max': '1200px',
        xl: '48px',
        sm: '8px',
        unit: '4px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'title-sm': ['16px', { lineHeight: '1.5', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['15px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'data-mono': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'display-lg': ['28px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
